Array creation


In [1]:
import numpy as np


In [2]:
arr=np.arange(15)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
arr_1=np.arange(20)

In [5]:
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
arr
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
arr=np.arange(15).reshape(3,5)

In [8]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
arr_1=np.arange(20).reshape(4,5)

In [10]:
arr_1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [11]:
print(arr.ndim)

2


In [12]:
print(arr_1.ndim)

2


In [13]:
print(arr.shape)

(3, 5)


In [14]:
print(arr_1.shape)

(4, 5)


In [15]:
print(arr.size)
print(arr_1.size)

15
20


In [16]:
print(arr.dtype)
print(arr_1.dtype)

int64
int64


In [17]:
print(arr.itemsize)

8


In [18]:
print(arr_1.itemsize)

8


In [19]:
print(type(arr))

<class 'numpy.ndarray'>


In [20]:
help(arr)

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

In [21]:
arr=np.array([5,6,7,8])

In [22]:
arr

array([5, 6, 7, 8])

In [23]:
print(arr.dtype)

int64


In [24]:
print(type(arr))

<class 'numpy.ndarray'>


In [25]:
arr=np.eye(10)
dtype=np.float(64)
print(arr)
print(dtype)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
64.0


In [26]:
a=np.linspace(-1,2,10,endpoint=True)
a

array([-1.        , -0.66666667, -0.33333333,  0.        ,  0.33333333,
        0.66666667,  1.        ,  1.33333333,  1.66666667,  2.        ])

In [27]:
a=np.linspace(-1,2,10,endpoint=False)
a

array([-1. , -0.7, -0.4, -0.1,  0.2,  0.5,  0.8,  1.1,  1.4,  1.7])

In [28]:
a=np.logspace(-1,2,10,endpoint=False)
a

array([ 0.1       ,  0.19952623,  0.39810717,  0.79432823,  1.58489319,
        3.16227766,  6.30957344, 12.58925412, 25.11886432, 50.11872336])

In [29]:
a=np.logspace(-1,2,10,endpoint=True)
a

array([  0.1       ,   0.21544347,   0.46415888,   1.        ,
         2.15443469,   4.64158883,  10.        ,  21.5443469 ,
        46.41588834, 100.        ])

In [30]:
a = np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)
a

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [31]:
f = np.fromfunction(lambda i, j: i == j, (2, 2), dtype=int)
f

array([[ True, False],
       [False,  True]])

Array_operation

In [32]:
arr=np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
arr*2


array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [34]:
arr+arr

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [35]:
arr_1=arr.transpose()
arr_1

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [36]:
arr@arr_1

array([[  30,   80,  130,  180],
       [  80,  255,  430,  605],
       [ 130,  430,  730, 1030],
       [ 180,  605, 1030, 1455]])

In [37]:
print(arr)
arr.sum(axis=1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([10, 35, 60, 85])

In [38]:
print(arr)
arr.sum(axis=0)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([30, 34, 38, 42, 46])

In [39]:
arr.sum()

190

In [40]:
print(arr.max())

19


In [41]:
print(arr.max(),arr.min())

19 0


universal function

In [42]:
b=arr*np.pi/20
b

array([[0.        , 0.15707963, 0.31415927, 0.4712389 , 0.62831853],
       [0.78539816, 0.9424778 , 1.09955743, 1.25663706, 1.41371669],
       [1.57079633, 1.72787596, 1.88495559, 2.04203522, 2.19911486],
       [2.35619449, 2.51327412, 2.67035376, 2.82743339, 2.98451302]])

In [43]:
c=np.cos(b)

In [44]:
c

array([[ 1.00000000e+00,  9.87688341e-01,  9.51056516e-01,
         8.91006524e-01,  8.09016994e-01],
       [ 7.07106781e-01,  5.87785252e-01,  4.53990500e-01,
         3.09016994e-01,  1.56434465e-01],
       [ 6.12323400e-17, -1.56434465e-01, -3.09016994e-01,
        -4.53990500e-01, -5.87785252e-01],
       [-7.07106781e-01, -8.09016994e-01, -8.91006524e-01,
        -9.51056516e-01, -9.87688341e-01]])

In [45]:
c=np.sin(b)
c

array([[0.        , 0.15643447, 0.30901699, 0.4539905 , 0.58778525],
       [0.70710678, 0.80901699, 0.89100652, 0.95105652, 0.98768834],
       [1.        , 0.98768834, 0.95105652, 0.89100652, 0.80901699],
       [0.70710678, 0.58778525, 0.4539905 , 0.30901699, 0.15643447]])

In [46]:
dd=b+c

In [47]:
dd

array([[0.        , 0.3135141 , 0.62317626, 0.9252294 , 1.21610378],
       [1.49250494, 1.75149479, 1.99056395, 2.20769358, 2.40140503],
       [2.57079633, 2.7155643 , 2.83601211, 2.93304175, 3.00813185],
       [3.06330127, 3.10105938, 3.12434426, 3.13645038, 3.14094749]])

Array Slicing

In [49]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr[1]

1

In [52]:
arr[7]

7

In [54]:
arr[2:6]

array([2, 3, 4, 5])

In [56]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr[1:10:3]

array([1, 4, 7])

In [69]:
num=np.arange(1000)
print(num)
even=num[0:100:2]
print(even)


[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

Multidimension


In [59]:
arr=np.arange(20).reshape(4,5)

In [60]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [61]:
a[1,2]

False

In [70]:
arr=np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [72]:
arr[1,2]

7

In [81]:
arr[1,4]

9

In [76]:
arr[2,2]

12

In [78]:
arr[0:2,0:2]

array([[0, 1],
       [5, 6]])

In [82]:
arr[0:4,0:4]

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [83]:
arr[:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [84]:
arr[:,1]

array([ 1,  6, 11])

In [85]:
arr[1,:]

array([5, 6, 7, 8, 9])

In [86]:
arr[2,:]

array([10, 11, 12, 13, 14])

In [88]:
arr=arr.flatten()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [90]:
for i in arr:
  print(i)

arr=np.arange(15).reshape(3,5)
arr

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

copying array

In [92]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [94]:
arr1=arr
arr1 is arr

True

In [96]:
arr1.shape=(2,5)
print(arr1)
arr.shape


[[0 1 2 3 4]
 [5 6 7 8 9]]


(2, 5)

In [97]:
arr1 is arr

True

In [98]:
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [106]:
arr=np.arange(15)
arr_1=arr[:]
arr.shape=(3,5)
print(arr)
print(arr_1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [107]:
arr_1[2]=-1
print(arr)
print(arr_1)

[[ 0  1 -1  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[ 0  1 -1  3  4  5  6  7  8  9 10 11 12 13 14]


In [108]:
arr_2=arr_1[2:9]

In [109]:
arr_2

array([-1,  3,  4,  5,  6,  7,  8])

In [111]:
arr_2[:]

array([-1,  3,  4,  5,  6,  7,  8])

In [112]:
print(arr)
print(arr_1)
print(arr_2)

[[ 0  1 -1  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[ 0  1 -1  3  4  5  6  7  8  9 10 11 12 13 14]
[-1  3  4  5  6  7  8]


In [113]:
print(arr_2 is arr)
print(arr_2.base is arr)
print(arr_2.flags.owndata)
print(arr.flags.owndata)

False
True
False
True


In [116]:
d=arr.copy()
d[:,:]=1.1
print(arr)
print(d)

[[ 0  1 -1  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


Boolean indexing

In [117]:
arr=np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [119]:
arr[arr>4]=0
arr

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [121]:
arr[arr==0]=-1
arr

array([[-1,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [124]:
arr=np.arange(12).reshape(3,4)
print(arr)
arr[np.logical_and(arr>3,arr<=9)]=0
arr

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  2,  3],
       [ 0,  0,  0,  0],
       [ 0,  0, 10, 11]])

In [125]:
arr>4

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True]])

In [127]:
A=30
B=50
xmin=ymin=0
xmax=ymax=1
x=np.linspace(xmin,xmax,A,endpoint=False)
y=np.linspace(xmin,xmax,B,endpoint=False)
print(x.shape)
print(y.shape)
y

(30,)
(50,)


array([0.  , 0.02, 0.04, 0.06, 0.08, 0.1 , 0.12, 0.14, 0.16, 0.18, 0.2 ,
       0.22, 0.24, 0.26, 0.28, 0.3 , 0.32, 0.34, 0.36, 0.38, 0.4 , 0.42,
       0.44, 0.46, 0.48, 0.5 , 0.52, 0.54, 0.56, 0.58, 0.6 , 0.62, 0.64,
       0.66, 0.68, 0.7 , 0.72, 0.74, 0.76, 0.78, 0.8 , 0.82, 0.84, 0.86,
       0.88, 0.9 , 0.92, 0.94, 0.96, 0.98])

In [128]:
import time
import numpy as np
M=32
N=64
x=np.linspace(0,1,M,endpoint=False)
y=np.linspace(0,1,N,endpoint=False)


In [131]:
t0=time.time()
g=np.zeros((M,N))
print(g)
for i in range(M):
  for j in range(N):
    g[i,j]=np.sin(2*np.pi*x[i]*y[j])
  
t1=time.time()
print("time elapsed {} s".format(t1-t0))


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
time elapsed 0.01165008544921875 s


In [132]:
x2d, y2d = np.meshgrid(x, y, indexing="ij")

print(x2d[:,0])
print(x2d[0,:])

print(y2d[:,0])
print(y2d[0,:])

[0.      0.03125 0.0625  0.09375 0.125   0.15625 0.1875  0.21875 0.25
 0.28125 0.3125  0.34375 0.375   0.40625 0.4375  0.46875 0.5     0.53125
 0.5625  0.59375 0.625   0.65625 0.6875  0.71875 0.75    0.78125 0.8125
 0.84375 0.875   0.90625 0.9375  0.96875]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
[0.       0.015625 0.03125  0.046875 0.0625   0.078125 0.09375  0.109375
 0.125    0.140625 0.15625  0.171875 0.1875   0.203125 0.21875  0.234375
 0.25     0.265625 0.28125  0.296875 0.3125   0.328125 0.34375  0.359375
 0.375    0.390625 0.40625  0.421875 0.4375   0.453125 0.46875  0.484375
 0.5      0.515625 0.53125  0.546875 0.5625   0.578125 0.59375  0.609375
 0.625    0.640625 0.65625  0.671875 0.6875   0.703125 0.71875  0.734375
 0.75     

In [133]:
t0 = time.time()
g2 = np.sin(2.0*np.pi*x2d*y2d)
t1 = time.time()
print("time elapsed: {} s".format(t1-t0))

time elapsed: 0.00025010108947753906 s


NumPy Standard Data Types

In [135]:
a=np.array([2,3,4,5])
b=np.array([6,7,8,9])
np.concatenate([a,b])

array([2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
c=[11,13,14,15]
np.concatenate([a,b,c])

array([ 2,  3,  4,  5,  6,  7,  8,  9, 11, 13, 14, 15])

In [138]:
a= np.array([[10, 20, 30],[40, 50, 60]])

In [140]:
np.concatenate([a,a],axis=1)

array([[10, 20, 30, 10, 20, 30],
       [40, 50, 60, 40, 50, 60]])

In [142]:
np.concatenate([a,a],axis=0)

array([[10, 20, 30],
       [40, 50, 60],
       [10, 20, 30],
       [40, 50, 60]])

splitting of array

In [146]:
x = [1, 2, 3, 4, 4, 3 ,2, 1, 9, 4 ,6,9,12,15]
x1, x2, x3,x4,x5 = np.split(x, [2,6,8,10])
print(x1, x2, x3, x4,x5)

[1 2] [3 4 4 3] [2 1] [9 4] [ 6  9 12 15]


In [149]:
g=np.arange(30).reshape((6,5))
g

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [150]:
left,right=np.hsplit(g,[2])
print(left)
print(right)

[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]
 [20 21]
 [25 26]]
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]
 [27 28 29]]


In [151]:
  left,right=np.hsplit(g,[3])
print(left)
print(right)

[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]
 [15 16 17]
 [20 21 22]
 [25 26 27]]
[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]
 [28 29]]


Aggregates

In [152]:
a=np.arange(1,9)
print(a)
np.add.reduce(a)

[1 2 3 4 5 6 7 8]


36

In [153]:
np.multiply.reduce(a)

40320

In [154]:
np.add.accumulate(a)

array([ 1,  3,  6, 10, 15, 21, 28, 36])

In [155]:
np.multiply.accumulate(a)

array([    1,     2,     6,    24,   120,   720,  5040, 40320])